### PR TITLE
Generate client-side bundle with Solid Style Guide

### LINKED ISSUE #26: Incorporate Inrupt's Solid Style Guide components
See https://design.inrupt.com/

### PR DESCRIPTION
**Pull request by Vinnl**
To be able to incorporate styles from Inrupt's Solid Style Guide
(see https://design.inrupt.com/), this commit introduces the
generation of HTML and CSS files in addition to the Javascript
files. This means that, instead of shipping their own HTML files,
Pod servers that host the data browser should now simply serve up
the `dist` directory in the Mashlib Node Module folder. This makes
sure that relative references to the CSS file keep working.

Since this would also require changes to node-solid-server, I suppose we shouldn't merge this until we decide to go ahead with this approach and have updated NSS as well - but comments are welcome.

Fixes #26.

### CODE REVIEW

**Comment by Vinnl** [comment]
I implemented the changes needed in node-solid-server to serve this in [the `mashlib-bundle` branch](https://github.com/solid/node-solid-server/compare/mashlib-bundle?expand=1). Nothing too invasive;  I'm guessing there's still some more stuff that could be removed as it should no longer be necessary - but I don't know enough of how NSS works to foresee what.

**Comment by megoth** [comment]
Can you make an accompanying PR for NSS? (It should load html files from mashlib instead of having its own, right? Also need to serve the necessary files for the data browser in general)

**Comment by Vinnl** [comment]
@megoth Created, the PR is here: https://github.com/solid/node-solid-server/pull/1218

I think it should be easier now for servers to embed mashlib, since they don't need to fork the HTML, but I guess time will tell :)

**Comment by Vinnl** [comment]
So @megoth, what's next? Merge this, publish to npm, then update https://github.com/solid/node-solid-server/pull/1218 to actually refer to the published package (and have its Travis builds succeed)?

**Comment by megoth** [comment]
> So @megoth, what's next? Merge this, publish to npm, then update [solid/node-solid-server#1218](https://github.com/solid/node-solid-server/pull/1218) to actually refer to the published package (and have its Travis builds succeed)?

Yes, with https://github.com/solid/node-solid-server/pull/1218 this is good to merge, so lets do that and publish to NPM.

**Comment by Vinnl** [comment]
Great, published as v0.8.0.

**Pull request merged**
