### PR TITLE
expose window.panes

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
I'm using this for https://mashlib-as-an-app.5apps.com/#resource=https%3A%2F%2Fmichielbdejong.inrupt.net%2Finbox%2F

**Comment by megoth** [comment]
This is a big question in terms of which API we expose, so want input from @timbl on this.

**Comment by michielbdejong** [comment]
ok! @megoth do you know how to get that app working, by the way? It's retrieving the resource, but not displaying it: https://mashlib-as-an-app.5apps.com/#resource=https%3A%2F%2Fmichielbdejong.inrupt.net%2Finbox%2F

(use the house icon to log in)

**Comment by megoth** [comment]
I think this is outdated and not needed anymore.

Please reopen if you disagree.

**Pull request closed without merging**
