### PR TITLE
Generate GH-pages HTML files again

### LINKED ISSUE #57: Data browser web app has vanished
https://solid.github.io/mashlib/dist/browse.html
used to be an online version of the databrowser,
which is quite handy for inspecting remote data. 
Like many RDF viewers on the web.

It has been removed in that dist is cleaned by out NPM run clean I suspect.

### PR DESCRIPTION
**Pull request by Vinnl**
This reverts commit d6055e3cd89d05cf0c87ebeeb590178d087267c8
and partially reverts commit
807eebb019cf79ed129b785c80105dd6ecbe60f2.

The HTML files that are expected to be deployed to GitHub Pages are
now located in the gh-pages directory, and copied to dist/ on
deployment to keep the URLs the same.

Fixes #57.

### CODE REVIEW

**Comment by Vinnl** [comment]
@RubenVerborgh As far as I can tell, the only reason those files exist are to be published to GitHub Pages - so a `gh-pages` directory seemed relevant. If you know of another reason those files exist, I could rename it to a more appropriate name.

The problem that this fixes is that `dist` usually (and currently in mashlib) contains build artifacts, i.e. files that do not belong in source control. That's how they got deleted last time.

**Comment by RubenVerborgh** [comment]
> the only reason those files exist are to be published to GitHub

They are also published on npm:
https://github.com/solid/mashlib/blob/4b8e97008aff46b15194a62b303854b7ab8723c1/package.json#L8

> That's how they got deleted last time.

Automatically or manually?

A `static` folder might do and, **as part of the _build_ process**, its files can be copied to `dist`.

**Comment by RubenVerborgh** [comment]
And we need validation (Travis) on the presence of files in `dist`, such that things like https://github.com/solid/mashlib/commit/807eebb019cf79ed129b785c80105dd6ecbe60f2 are flagged automatically.

**Comment by Vinnl** [comment]
> They are also published on npm

They can be - do they need to be? They aren't currently, and I haven't seen any Issues filed about that. Which use case does that fit?

> Automatically or manually?

Manually.

> A static folder might do

Great, I'll rename it.

> and, as part of the build process, its files can be copied to dist.

If it needs to be published to npm, sure.

**Comment by RubenVerborgh** [comment]
> They can be - do they need to be?

Yes.

> They aren't currently, and I haven't seen any Issues filed about that.

Then we can still fix it on time 🙂

**Comment by Vinnl** [comment]
>> They can be - do they need to be?
> 
> Yes.

I'd still be interested in hearing the use case for this - another important reason this happened was that both Arne and I weren't even aware of the use case in #57 so it wasn't caught in review, so being aware of use cases would be helpful :)

**Comment by RubenVerborgh** [comment]
> the use case for this

It's how Node modules serve mashlib: https://github.com/solid/node-solid-server/blob/0555e66f35ea0248a45bbe5249a125d4fb15b53e/lib/create-app.js#L70

**Comment by Vinnl** [comment]
@RubenVerborgh Node Solid Server you mean, I presume? The line you referenced would indeed serve up `databrowser.html` and `browse.html`, but it's actually intended to just serve the JS, CSS and `index.html` - as you can see in [the commit that introduced that line](https://github.com/solid/node-solid-server/commit/e364266629cee5606070778cda25abd7664528e7) (which was added at the same time as `databrowser.html` was removed). In other words: NSS has never served up `browse.html`, and used to use `databrowser.html` for the functionality now provided by `src/index.html`. So as far as I can see, NSS does not actually need those files.

If that's the only use case, then I'd prefer to leave it at `gh-pages`; that makes it clear to future developers whether it can be removed or not (i.e. whether GitHub Pages still exists and we're still using it).

**Comment by Vinnl** [comment]
Note: I just noticed I'd reverted too much. The diff is a bit smaller now.

**Comment by mikeadams1** [comment]
Why not just create a separate /dist repo for them?

**Comment by Vinnl** [comment]
@mikeadams1 A separate repository would also result in different URLs, so people's bookmarks would still be broken...

**Comment by mikeadams1** [comment]
For me it is far easier to change a URL then it is for this to not cause havoc. Also, as you previously mentioned in https://github.com/solid/mashlib/issues/57, there will be breakage at some point so, it would be much easer for all parties to just put them into a separate /dist repo and mention it on gitter.

**Comment by Vinnl** [comment]
The precise bug this fixes is caused by the files no longer being available at that specific URL. The best approach would still be for people to copy the files to a location they control, and that cannot be tracked by GitHub/Microsoft.

Note that the breakage is not caused by the file being part of this repository, but by the CSS being updated - which will happen anyway, and which is necessarily a part of this repository.

This is also the reason that moving it to a new repository wouldn't work: the HTML files there would reference files that are part of this repository, and thus would not be available, unfortunately.

(What would you want mentioned on Gitter, btw? Would that not be possible with this repository as well?)

**Comment by RubenVerborgh** [comment]
Regarding breakage: we need tests for this.

**Comment by mikeadams1** [comment]
Currently, there is no 

> (What would you want mentioned on Gitter, btw?

For those depending on it to know where to find it.





> Would that not be possible with this repository as well?)

Most certainly. 





> The best approach would still be for people to copy the files to a location they control, and that cannot be tracked by GitHub/Microsoft.

I agree, and as mentioned in #57, I have begun doing that.

**Comment by Vinnl** [comment]
Tim's comment at https://github.com/solid/mashlib/pull/63#issuecomment-523670182 made me realise that `databrowser.html` is actually the file that's generated by Webpack, so I've removed the hardcoded one here. #63 will make sure that it's actually called `databrowser.html` and is generated again.

**Comment by megoth** [comment]
https://github.com/solid/mashlib/pull/62 was favored solution, closing this PR.

**Pull request closed without merging**
