### PR TITLE
Add payment pointer to page header

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
Related to:
* https://github.com/solid/contacts-pane/pull/36
* https://github.com/solid/node-solid-server/pull/1546
* https://github.com/solid/webmonetization/issues/1

**Comment by michielbdejong** [comment]
Screenshot 2021-01-13 at 16 05 58

**Comment by michielbdejong** [comment]
Let's discuss in [today's Solid OS meeting](https://solidos.solidcommunity.net/Team/2020/schedule/solidos-schedule.html)

**Comment by angelo-v** [comment]
so this adds window.location.host to the header, which is user specific on NSS, but not necessarily on other Solid servers, e.g. Inrupt Pod Spaces, where it will be pod.inrupt.com for every user. Is this an issue? Also what about Solid Servers that do not implement webmonitization at all?

**Comment by michielbdejong** [comment]
This PR just adds one step in the path - from html page to web server.
It allows the host (web server) of the Solid OS instance to monetise it by setting up /.well-known/pay.
There is no assumption that this host is an NSS instance, or even a pod server. It could just be hosted as a static web app.
If /.well-known/pay is not set up then nothing happens.
If the html page is viewed with a browser that doesn't support Web Monetisation (or indeed if embedded in desktop application like the Data Kitchen) then nothing happens.

**Review by angelo-v — APPROVED** [review]

**Comment by michielbdejong** [comment]
Thanks!

**Pull request merged**
