### PR TITLE
Try move auth

### PR DESCRIPTION
**Pull request by theRealImy**
This is the PR for the move auth from solid-ui to solid-logic.

### CODE REVIEW

**Comment by theRealImy** [comment]
@jeff-zucker When you have time take a look at the PR, particularly the file static/browse.html and check how repos are used from mashlib now. UI is directly used and cannot be exported from panes.UI anymore. Unless I put the UI to be exported form solid-panes back -> see this PR too: https://github.com/solid/solid-panes/pull/337

**Review by timbl — APPROVED** [review]

**Comment by jeff-zucker** [comment]
I'm sorry, I really do not like these changes.  There are dozens and dozens of places across many libraries that use panes.UI and panes.UI.authn.  Introducing a new way of exorting in addition is fine, but I strongly object to making all of these backward-incompatible changes.  If these are instituted, it will really have to be a major version release.

**Comment by theRealImy** [comment]
Follow up on the usage of the global variables: I found out in solid-ui in the openHrefInOutlineMode function we make use of window.panes -> panes here is solid-panes. This introduces a cyclic dependency in our repo -> needs to get refactored out.
Consequence: make sure panes is added to the window global variable.  also: window.panes.getOutliner, window.panes.UI

**Comment by theRealImy** [comment]
> Are you talking about how these things are addressed internally or how they are exported? Because exporting window.panes but not panes will break everything. Not sure if that is what you are suggesting, but if so that will break backwards compatability.

@jeff-zucker I am talking about this line of code in solid-ui: https://github.com/solid/solid-ui/blob/707601b18fc26917752ae0150bdc55058a34312e/src/widgets/buttons.ts#L987 -> this really really bad!

**Comment by jeff-zucker** [comment]
So to whom is the advice "use window.panes not panes" addressed to and in what circumstance would it be used?

**Comment by jeff-zucker** [comment]
Isn't that line just saying that if there is no outliner but there is a winodw.panes.outliner, use that outliner?  How is that bad?

**Comment by jeff-zucker** [comment]
Also why do you believe that other code should create window.panes?

**Comment by theRealImy** [comment]
The questions above were addressed in a one on one chat. Some conclusions:
* when using mashlib, all variables exported in all repos are actually global variables in mashlib by default. 
* windows.panes is the same variable like panes (when using mashlib as in import mashlib.js in integration projects)
* one can use panes.UI as well as UI directly (when using mashlib as in import mashlib.js in integration projects) this was ALWAYS possible and not new, introduced with this refactoring
* going forward with the PR -> no backward compatibility will be broken
* proper documentation on the variables exposed and accessible when one uses mashlib in integrations will follow this refactoring.

**Pull request merged**
